#!/usr/bin/env python3
"""Review visual reference assets in a storyboard director pack."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path

DIRECTOR_SCRIPT_DIR = Path(__file__).resolve().parents[2] / "storyboard-video-director" / "scripts"
if str(DIRECTOR_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(DIRECTOR_SCRIPT_DIR))

from control_strategy_requirements import infer_requirements

try:
    from PIL import Image
except Exception:  # noqa: BLE001
    Image = None  # type: ignore[assignment]


REPORT_NAME = "15_visual_asset_review.md"
JSON_REPORT_NAME = "15_visual_asset_review.json"
IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp"}
SCHEMATIC_EXTS = {".svg"}


@dataclass
class AssetReview:
    role: str
    status: str
    path: str
    exists: bool
    width: int | None
    height: int | None
    verdict: str
    notes: list[str]


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def image_size(path: Path) -> tuple[int | None, int | None]:
    if Image is None or not path.exists() or path.suffix.lower() not in IMAGE_EXTS:
        return None, None
    try:
        with Image.open(path) as image:
            return image.size
    except Exception:  # noqa: BLE001
        return None, None


def image_files(path: Path) -> list[Path]:
    if path.is_dir():
        return sorted(item for item in path.iterdir() if item.suffix.lower() in IMAGE_EXTS)
    if path.is_file() and path.suffix.lower() in IMAGE_EXTS:
        return [path]
    return []


def schematic_files(path: Path) -> list[Path]:
    if path.is_dir():
        return sorted(item for item in path.iterdir() if item.suffix.lower() in SCHEMATIC_EXTS)
    if path.is_file() and path.suffix.lower() in SCHEMATIC_EXTS:
        return [path]
    return []


def role_notes(role: str, status: str, exists: bool, path_value: str, width: int | None, height: int | None) -> tuple[str, list[str]]:
    notes: list[str] = []
    verdict = "PASS"

    if status == "not_needed":
        return "SKIPPED", [f"{role} is explicitly marked not_needed in the manifest."]

    if status == "missing":
        severity = "FAIL" if role in {"storyboard_control"} else "MISSING"
        return severity, [f"{role} is missing from the manifest."]

    if status in {"generated", "user_supplied", "prompt_only"} and path_value and not exists:
        return "FAIL", [f"{role} path is registered but does not exist: {path_value}"]

    if status == "prompt_only":
        verdict = "PROMPT ONLY"
        notes.append(f"{role} has a prompt but no real image asset yet.")

    if exists and width and height:
        notes.append(f"image size: {width}x{height}")
        if width < 1024 or height < 576:
            verdict = "WARN" if verdict == "PASS" else verdict
            notes.append("resolution may be low for downstream reference use.")
    elif exists:
        verdict = "WARN" if verdict == "PASS" else verdict
        notes.append("image exists but size could not be inspected.")

    if role == "storyboard_control":
        notes.append("must be a raster image generated by image2/image generation or user-supplied real image for preflight/production.")
        notes.append("SVG/programmatic diagrams are schematic aids only and do not satisfy storyboard_control.")
        notes.append("allowed to contain panel borders, numbers, arrows, notes, and colored motion guides.")
        notes.append("must be used only for choreography, timing, camera, staging, and panel order.")
    elif role == "character_reference":
        notes.append("should be clean identity/costume reference; labels are acceptable for reference use but not for clean keyframes.")
        notes.append("must not be treated as storyboard control.")
    elif role == "prop_reference":
        notes.append("should lock prop silhouette, scale, states, material, and forbidden mutations.")
        notes.append("labels are acceptable for reference use but not for clean keyframes.")
    elif role == "environment_reference":
        notes.append("should lock geography, platforms, props, lighting, and spatial continuity when environment is action-critical.")
    elif role == "style_reference":
        notes.append("should lock rendering finish, line quality, color, lens tone, and completion level.")
    elif role == "clean_keyframe_reference":
        notes.append("must not contain text, panel borders, arrows, notes, UI, or annotations.")

    return verdict, notes


def review_assets(package_dir: Path, manifest: dict) -> list[AssetReview]:
    assets = manifest.get("reference_assets", {})
    if not isinstance(assets, dict):
        return [
            AssetReview(
                role="reference_assets",
                status="missing",
                path="",
                exists=False,
                width=None,
                height=None,
                verdict="FAIL",
                notes=["manifest.reference_assets is missing or invalid."],
            )
        ]

    reviews: list[AssetReview] = []
    for role, asset in assets.items():
        if not isinstance(asset, dict):
            reviews.append(
                AssetReview(role, "invalid", "", False, None, None, "FAIL", [f"{role} asset entry is not an object."])
            )
            continue
        status = str(asset.get("status", "missing"))
        path_value = str(asset.get("path") or "")
        path = package_dir / path_value if path_value else package_dir / "__missing__"
        exists = bool(path_value) and path.exists()
        files = image_files(path)
        schematics = schematic_files(path)
        inspected_path = files[0] if files else path
        width, height = image_size(inspected_path)
        verdict, notes = role_notes(role, status, exists, path_value, width, height)
        if schematics and not files:
            notes.insert(0, f"schematic/SVG file count: {len(schematics)}.")
            if role == "storyboard_control":
                verdict = "FAIL"
                notes.append("storyboard_control is schematic-only; generate a raster storyboard control image with image2/image generation.")
            else:
                verdict = "SCHEMATIC ONLY" if verdict == "PASS" else verdict
                notes.append("schematic-only asset may be useful as a map/debug aid but is not a production visual reference.")
        elif schematics:
            notes.insert(0, f"schematic/SVG file count: {len(schematics)} alongside raster images.")
        if path.is_dir():
            notes.insert(0, f"image directory contains {len(files)} supported image(s).")
            if status in {"generated", "user_supplied"} and not files:
                verdict = "FAIL"
                notes.append("generated/user-supplied directory must contain at least one image.")
        reviews.append(AssetReview(role, status, path_value, exists, width, height, verdict, notes))
    return reviews


def overall_verdict(reviews: list[AssetReview], strict_assets: bool, required_roles: set[str] | None = None) -> str:
    required_roles = required_roles or set()
    if any(review.verdict == "FAIL" for review in reviews):
        return "FAIL"
    if any(
        review.role in required_roles
        and review.status != "not_needed"
        and review.verdict in {"MISSING", "PROMPT ONLY"}
        for review in reviews
    ):
        return "FAIL" if strict_assets else "PASS WITH GAPS"
    if strict_assets and any(
        review.verdict in {"MISSING", "PROMPT ONLY"}
        for review in reviews
        if review.role != "clean_keyframe_reference" and review.status != "not_needed"
    ):
        return "FAIL"
    if any(review.verdict in {"WARN", "MISSING", "PROMPT ONLY", "SCHEMATIC ONLY"} for review in reviews):
        return "PASS WITH GAPS"
    return "PASS"


def write_reports(package_dir: Path, manifest: dict, reviews: list[AssetReview], strict_assets: bool) -> Path:
    requirements = infer_requirements(package_dir, manifest)
    verdict = overall_verdict(reviews, strict_assets, requirements.required_assets)
    report_path = package_dir / REPORT_NAME
    preserved_manual = ""
    manual_marker = "\n## Manual Visual Findings\n"
    if report_path.exists():
        existing = report_path.read_text(encoding="utf-8-sig")
        if manual_marker in existing:
            preserved_manual = "## Manual Visual Findings\n" + existing.split(manual_marker, 1)[1].strip()

    lines = [
        "# Visual Asset Review",
        "",
        f"- Verdict: {verdict}",
        f"- Strict asset review: {'enabled' if strict_assets else 'disabled'}",
        f"- Project: {manifest.get('project_title', 'not recorded')}",
        "",
    ]
    lines.extend(
        [
            "## Strategy-Specific Requirements",
            "",
            f"- Inferred strategies: {', '.join(sorted(requirements.strategies)) or 'none'}",
            f"- Required real assets: {', '.join(sorted(requirements.required_assets)) or 'none'}",
            f"- Recommended assets: {', '.join(sorted(requirements.recommended_assets)) or 'none'}",
            f"- Semantic visual checks: {', '.join(sorted(requirements.semantic_checks)) or 'none'}",
            "",
        ]
    )
    if requirements.notes:
        lines.extend(["Notes:", *[f"- {note}" for note in requirements.notes], ""])

    lines.extend(["## Asset Role Checks", ""])
    for review in reviews:
        lines.extend(
            [
                f"### {review.role}",
                "",
                f"- Verdict: {review.verdict}",
                f"- Status: {review.status}",
                f"- Path: {review.path or 'none'}",
                f"- Exists: {'yes' if review.exists else 'no'}",
                "",
                "Notes:",
                *[f"- {note}" for note in review.notes],
                "",
            ]
        )

    lines.extend(
        [
            "## Manual Review Checklist",
            "",
            "- Storyboard control: panel order, camera movement, action path, timing, and final payoff are readable.",
            "- Character reference: identity, proportions, costume, hair, expression range, and palette are consistent.",
            "- Prop reference: closed/open states, scale, material, grip, and forbidden mutations are unambiguous.",
            "- Environment reference: action geography and spatial continuity are available if the scene depends on them.",
            "- Style reference: rendering finish and color/line language are available if style fidelity matters.",
            "- Clean keyframes: no labels, no arrows, no panel borders, no UI, no subtitles, no annotations.",
        ]
    )
    if preserved_manual:
        lines.extend(["", preserved_manual])

    report_path.write_text("\n".join(lines).strip() + "\n", encoding="utf-8")

    json_path = package_dir / JSON_REPORT_NAME
    json_path.write_text(
        json.dumps(
            {
                "verdict": verdict,
                "strict_assets": strict_assets,
                "reviews": [review.__dict__ for review in reviews],
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )
    return report_path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("package_dir", help="Storyboard director pack directory.")
    parser.add_argument("--strict-assets", action="store_true", help="Fail if real central visual assets are missing.")
    args = parser.parse_args()

    package_dir = Path(args.package_dir).expanduser().resolve()
    manifest_path = package_dir / "10_generation_manifest.json"
    if not manifest_path.exists():
        print(f"ERROR: missing manifest: {manifest_path}")
        return 1
    try:
        manifest = load_json(manifest_path)
    except Exception as exc:  # noqa: BLE001
        print(f"ERROR: manifest is not valid JSON: {exc}")
        return 1

    reviews = review_assets(package_dir, manifest)
    report_path = write_reports(package_dir, manifest, reviews, args.strict_assets)
    requirements = infer_requirements(package_dir, manifest)
    verdict = overall_verdict(reviews, args.strict_assets, requirements.required_assets)
    print(f"Visual asset review verdict: {verdict}")
    print(f"Wrote report: {report_path}")
    for review in reviews:
        print(f"- {review.verdict}: {review.role} ({review.status}) {review.path or ''}".strip())
    return 1 if verdict == "FAIL" else 0


if __name__ == "__main__":
    raise SystemExit(main())
